//! The licence every package carries must not drift from its sources.
//!
//! `src-tauri/LICENSE-bundle.txt` is the root `LICENSE` followed by the
//! Business Source License 1.1 of `src-tauri/src/pro/` and `src/lib/pro/`,
//! generated by `scripts/gen-license-bundle.mjs` (same format as here). Every
//! bundle ships it; the Linux packages also carry the pro licences under
//! /usr/share/doc. The installers' licence page shows
//! `src-tauri/LICENSE-installer.txt`: the same words, one line per paragraph,
//! because that page wraps lines itself.

use std::fs;
use std::path::{Path, PathBuf};

fn manifest_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
}

fn read(path: &Path) -> String {
    fs::read_to_string(path)
        .unwrap_or_else(|e| panic!("{}: {}", path.display(), e))
        .replace("\r\n", "\n")
}

#[test]
fn license_bundle_is_license_plus_pro_licenses() {
    let dir = manifest_dir();
    let sources = [dir.join("../LICENSE"), dir.join("src/pro/LICENSE"), dir.join("../src/lib/pro/LICENSE")];
    let separator = format!("\n\n{}\n\n", "=".repeat(77));
    let expected = sources.iter().map(|p| read(p).trim_end().to_string()).collect::<Vec<_>>().join(&separator) + "\n";
    let actual = read(&dir.join("LICENSE-bundle.txt"));
    assert!(
        actual == expected,
        "src-tauri/LICENSE-bundle.txt is out of date: run `node scripts/gen-license-bundle.mjs`"
    );
}

/// The words of a licence text, rules of = or - left out: the installer
/// text may lay them out differently, never change them.
fn words(text: &str) -> Vec<String> {
    text.split_whitespace()
        .filter(|w| !(w.len() >= 5 && (w.chars().all(|c| c == '=') || w.chars().all(|c| c == '-'))))
        .map(str::to_string)
        .collect()
}

#[test]
fn installer_license_has_the_same_words_as_the_bundle() {
    let dir = manifest_dir();
    let bundle = read(&dir.join("LICENSE-bundle.txt"));
    let installer = read(&dir.join("LICENSE-installer.txt"));
    assert!(
        words(&installer) == words(&bundle),
        "src-tauri/LICENSE-installer.txt differs from LICENSE-bundle.txt: run `node scripts/gen-license-bundle.mjs`"
    );
    // Laid out for a box that wraps by itself: no hard-wrapped paragraph
    // lines and no rule wider than the box.
    for line in installer.lines() {
        let rule = line.len() >= 5 && (line.chars().all(|c| c == '=') || line.chars().all(|c| c == '-'));
        assert!(!rule || line.len() <= 20, "rule too wide for the licence page: {line}");
    }
}

#[test]
fn packages_reference_the_license_files() {
    let dir = manifest_dir();
    let conf: serde_json::Value = serde_json::from_str(&read(&dir.join("tauri.conf.json"))).unwrap();
    let bundle = &conf["bundle"];
    assert_eq!(bundle["licenseFile"], "LICENSE-installer.txt");
    assert_eq!(bundle["resources"]["LICENSE-bundle.txt"], "LICENSE.txt");
    for pkg in ["deb", "rpm"] {
        let files = &bundle["linux"][pkg]["files"];
        assert_eq!(files["/usr/share/doc/bridgelab/copyright"], "../LICENSE", "{pkg}");
        assert_eq!(files["/usr/share/doc/bridgelab/LICENSE-pro"], "src/pro/LICENSE", "{pkg}");
        assert_eq!(files["/usr/share/doc/bridgelab/LICENSE-pro-ui"], "../src/lib/pro/LICENSE", "{pkg}");
    }
}
