//! XSD generator for HL7 v2.xml message schemas.
//!
//! Emits a self-contained XSD that matches the HL7 v2.xml encoding
//! convention: one root element per message, one complex type per segment
//! group, and each field expressed as `xs:string` with `xs:maxLength`.
//!
//! F1 limitations (documented in the output header):
//! * no composite data type expansion (every field is `xs:string`);
//! * no value-table (`xs:enumeration`) constraints;
//! * `Z-segments` are not represented.
//!
//! These are the first additions in F2.

use super::{Hl7Schema, MessageElement, MessageStructure, SegmentSpec};
use std::fmt::Write;

/// Generate the XSD text for `message_code` (e.g. `ADT_A01`) against the
/// supplied schema. Returns `Err` if the message isn't defined.
pub fn generate_xsd(schema: &Hl7Schema, message_code: &str) -> Result<String, String> {
    let message = schema
        .message(message_code)
        .ok_or_else(|| format!("Message '{}' not found in HL7 v{}", message_code, schema.version.as_str()))?;

    let mut out = String::with_capacity(16 * 1024);
    write_header(&mut out, schema, message);
    writeln!(out, r#"<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">"#).unwrap();

    // Root element → main complex type
    writeln!(out).unwrap();
    writeln!(out, r#"  <xs:element name="{code}" type="{code}.CONTENT"/>"#, code = message.code).unwrap();
    writeln!(out).unwrap();
    writeln!(out, r#"  <xs:complexType name="{code}.CONTENT">"#, code = message.code).unwrap();
    writeln!(out, "    <xs:sequence>").unwrap();
    emit_elements(&mut out, &message.elements, &format!("{}.", message.code), 3);
    writeln!(out, "    </xs:sequence>").unwrap();
    writeln!(out, "  </xs:complexType>").unwrap();

    // Nested group complex types
    emit_group_types(&mut out, &message.elements, &format!("{}.", message.code));

    // Each segment used by the message gets its own complex type
    let mut used_segments = schema.segments_used_by(&message.code);
    used_segments.sort();
    for code in &used_segments {
        if let Some(seg) = schema.segment(code) {
            emit_segment_type(&mut out, seg);
        }
    }

    writeln!(out).unwrap();
    writeln!(out, "</xs:schema>").unwrap();
    Ok(out)
}

fn write_header(out: &mut String, schema: &Hl7Schema, message: &MessageStructure) {
    writeln!(out, r#"<?xml version="1.0" encoding="UTF-8"?>"#).unwrap();
    writeln!(out, "<!--").unwrap();
    writeln!(out, "  XSD for HL7 v{} message {}", schema.version.as_str(), message.event).unwrap();
    writeln!(out, "  ({})", message.description).unwrap();
    writeln!(out, "  Generated by BridgeLab (TECHEMV SRL).").unwrap();
    writeln!(out, "  Based on public HL7 v2.x specifications. HL7 is a registered").unwrap();
    writeln!(out, "  trademark of Health Level Seven International. This schema is a").unwrap();
    writeln!(out, "  derivative work for interoperability purposes.").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "  F1 limitations: composite data types are expanded as xs:string.").unwrap();
    writeln!(out, "  Value-table enumerations are not applied. Future versions will").unwrap();
    writeln!(out, "  tighten these restrictions.").unwrap();
    writeln!(out, "-->").unwrap();
}

fn emit_elements(out: &mut String, elements: &[MessageElement], group_prefix: &str, indent_depth: usize) {
    let pad = "  ".repeat(indent_depth);
    for e in elements {
        match e {
            MessageElement::Segment { code, required, repeats } => {
                writeln!(
                    out,
                    r#"{pad}<xs:element ref="{code}" minOccurs="{min}" maxOccurs="{max}"/>"#,
                    pad = pad,
                    code = code,
                    min = if *required { 1 } else { 0 },
                    max = if *repeats { "unbounded" } else { "1" },
                ).unwrap();
            }
            MessageElement::Group { name, required, repeats, elements: _ } => {
                writeln!(
                    out,
                    r#"{pad}<xs:element name="{name}" type="{prefix}{name}.CONTENT" minOccurs="{min}" maxOccurs="{max}"/>"#,
                    pad = pad,
                    name = name,
                    prefix = group_prefix,
                    min = if *required { 1 } else { 0 },
                    max = if *repeats { "unbounded" } else { "1" },
                ).unwrap();
            }
        }
    }
}

fn emit_group_types(out: &mut String, elements: &[MessageElement], prefix: &str) {
    for e in elements {
        if let MessageElement::Group { name, elements: inner, .. } = e {
            writeln!(out).unwrap();
            writeln!(out, r#"  <xs:complexType name="{prefix}{name}.CONTENT">"#, prefix = prefix, name = name).unwrap();
            writeln!(out, "    <xs:sequence>").unwrap();
            // Nested groups use their own prefix so inner groups don't collide with other messages' identically-named groups.
            let inner_prefix = format!("{}{}.", prefix, name);
            emit_elements(out, inner, &inner_prefix, 3);
            writeln!(out, "    </xs:sequence>").unwrap();
            writeln!(out, "  </xs:complexType>").unwrap();
            emit_group_types(out, inner, &inner_prefix);
        }
    }
}

fn emit_segment_type(out: &mut String, seg: &SegmentSpec) {
    writeln!(out).unwrap();
    writeln!(out, r#"  <xs:element name="{code}" type="{code}.CONTENT"/>"#, code = seg.code).unwrap();
    writeln!(out, r#"  <xs:complexType name="{code}.CONTENT">"#, code = seg.code).unwrap();
    writeln!(out, "    <xs:sequence>").unwrap();
    for field in &seg.fields {
        let min = if field.required { 1 } else { 0 };
        let max = if field.repeats { "unbounded".to_string() } else { "1".to_string() };
        let padded = format!("{}.{}", seg.code, field.position);
        // HL7 XSDs conventionally name fields like <PID.5> with the Name as documentation.
        writeln!(out, r#"      <xs:element name="{name}" minOccurs="{min}" maxOccurs="{max}">"#,
            name = padded, min = min, max = max).unwrap();
        writeln!(out, r#"        <xs:annotation><xs:documentation>{}</xs:documentation></xs:annotation>"#,
            xml_escape(&field.name)).unwrap();
        writeln!(out, "        <xs:simpleType>").unwrap();
        writeln!(out, r#"          <xs:restriction base="xs:string">"#).unwrap();
        if let Some(max_len) = field.max_length {
            writeln!(out, r#"            <xs:maxLength value="{}"/>"#, max_len).unwrap();
        }
        writeln!(out, "          </xs:restriction>").unwrap();
        writeln!(out, "        </xs:simpleType>").unwrap();
        writeln!(out, "      </xs:element>").unwrap();
    }
    writeln!(out, "    </xs:sequence>").unwrap();
    writeln!(out, "  </xs:complexType>").unwrap();
}

fn xml_escape(s: &str) -> String {
    s.replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;")
        .replace('\'', "&apos;")
}

#[cfg(test)]
mod tests {
    use super::super::{load, Hl7Version};
    use super::*;

    #[test]
    fn adt_a01_xsd_contains_expected_elements() {
        let s = load(Hl7Version::V2_5);
        let xsd = generate_xsd(&s, "ADT_A01").unwrap();

        // Declaration
        assert!(xsd.starts_with("<?xml"));
        // Root element
        assert!(xsd.contains(r#"<xs:element name="ADT_A01" type="ADT_A01.CONTENT"/>"#));
        // Every referenced segment has a complexType
        for seg in ["MSH", "EVN", "PID", "PV1", "OBX", "AL1", "DG1"] {
            let name_tag = format!(r#"<xs:element name="{}" type="{}.CONTENT"/>"#, seg, seg);
            assert!(xsd.contains(&name_tag), "missing segment declaration {}", seg);
        }
        // INSURANCE group has its own complex type
        assert!(xsd.contains("ADT_A01.INSURANCE.CONTENT"));
        // IN1 inside the group is referenced
        assert!(xsd.contains(r#"ref="IN1""#));
    }

    #[test]
    fn orm_o01_has_nested_group_types() {
        let s = load(Hl7Version::V2_5);
        let xsd = generate_xsd(&s, "ORM_O01").unwrap();

        // Top-level groups
        assert!(xsd.contains("ORM_O01.PATIENT.CONTENT"));
        assert!(xsd.contains("ORM_O01.ORDER.CONTENT"));
        // Nested groups use composite names so they don't collide
        assert!(xsd.contains("ORM_O01.ORDER.ORDER_DETAIL.CONTENT"));
        assert!(xsd.contains("ORM_O01.ORDER.ORDER_DETAIL.OBSERVATION.CONTENT"));
    }

    #[test]
    fn adt_a40_has_mrg_segment_and_patient_group() {
        let s = load(Hl7Version::V2_5);
        let xsd = generate_xsd(&s, "ADT_A40").unwrap();

        assert!(xsd.contains(r#"<xs:element name="MRG" type="MRG.CONTENT"/>"#));
        assert!(xsd.contains("ADT_A40.PATIENT.CONTENT"));
    }

    #[test]
    fn oru_r01_deeply_nested_groups() {
        let s = load(Hl7Version::V2_5);
        let xsd = generate_xsd(&s, "ORU_R01").unwrap();

        assert!(xsd.contains("ORU_R01.PATIENT_RESULT.CONTENT"));
        assert!(xsd.contains("ORU_R01.PATIENT_RESULT.PATIENT.CONTENT"));
        assert!(xsd.contains("ORU_R01.PATIENT_RESULT.ORDER_OBSERVATION.OBSERVATION.CONTENT"));
    }

    #[test]
    fn unknown_message_returns_error() {
        let s = load(Hl7Version::V2_5);
        assert!(generate_xsd(&s, "FOO_BAR").is_err());
    }

    #[test]
    fn field_maxlength_is_emitted() {
        let s = load(Hl7Version::V2_5);
        let xsd = generate_xsd(&s, "ADT_A01").unwrap();
        // PID.19 (SSN) has max_length 16
        assert!(xsd.contains(r#"<xs:maxLength value="16"/>"#),
            "expected maxLength=16 somewhere in the XSD");
    }

    #[test]
    fn produces_valid_xml_like_structure() {
        let s = load(Hl7Version::V2_5);
        let xsd = generate_xsd(&s, "ADT_A01").unwrap();
        // Basic balance check — open/close tag counts should match for the schema root
        let open_schema = xsd.matches("<xs:schema").count();
        let close_schema = xsd.matches("</xs:schema>").count();
        assert_eq!(open_schema, close_schema, "schema tag imbalance");

        let open_complex = xsd.matches("<xs:complexType").count();
        let close_complex = xsd.matches("</xs:complexType>").count();
        assert_eq!(open_complex, close_complex, "complexType imbalance");

        let open_seq = xsd.matches("<xs:sequence>").count();
        let close_seq = xsd.matches("</xs:sequence>").count();
        assert_eq!(open_seq, close_seq, "sequence imbalance");
    }
}
